### ISSUE TITLE
Error in density.default(df1) :    need at least 2 points to select a bandwidth automatically

### ISSUE THREAD

**Issue by 745757** [haotian-zhuang/findPC#1]
When I run the following code using the sample data"procdata",error occurs:
library(findPC)
data(procdata)
sdev<-prcomp(t(procdata),scale. = T)$sdev[1:50]
head(sdev)
findPC(sdev = sdev, 
       number = 1:30, 
       method = 'all', 
       figure = T    
)

Error in density.default(df1) : 
  need at least 2 points to select a bandwidth automatically

I don't know how to solve this problem

**Comment by haotian-zhuang** [comment]
> When I run the following code using the sample data"procdata",error occurs: library(findPC) data(procdata) sdev<-prcomp(t(procdata),scale. = T)$sdev[1:50] head(sdev) findPC(sdev = sdev, number = 1:30, method = 'all', figure = T )
> 
> Error in density.default(df1) : need at least 2 points to select a bandwidth automatically
> 
> I don't know how to solve this problem

Hello,
Please note that if you want to consider the top 30 PCs, use number = 30 instead of 1:30. The method does not work when you consider a very small number of PCs, but I have tested that it works for number = 5:30.
Best,
